// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD18s5Xl4Fbx5gyZpAJZZWJDg-0mDXYS-A',
    appId: '1:802280398317:web:6579fc13642a9dc8cfdbe4',
    messagingSenderId: '802280398317',
    projectId: 'foldious-ae650',
    authDomain: 'foldious-ae650.firebaseapp.com',
    storageBucket: 'foldious-ae650.firebasestorage.app',
    measurementId: 'G-CYMH0HZL0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1E-FIcn3oT6Z0oDjziwh9wVB8bCgN0uU',
    appId: '1:802280398317:android:35982017ca17e7cfcfdbe4',
    messagingSenderId: '802280398317',
    projectId: 'foldious-ae650',
    storageBucket: 'foldious-ae650.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEPMOaCeY7YyM6ENyEdl7L9G8Au6awvGY',
    appId: '1:802280398317:ios:ba67122c33e765fdcfdbe4',
    messagingSenderId: '802280398317',
    projectId: 'foldious-ae650',
    storageBucket: 'foldious-ae650.firebasestorage.app',
    androidClientId: '802280398317-70o4469n74hpjsspln2vhi81iu0d1qm0.apps.googleusercontent.com',
    iosClientId: '802280398317-4lhcvq0t5v8j0c5hgnmqdu96totg923r.apps.googleusercontent.com',
    iosBundleId: 'com.foldious.storage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEPMOaCeY7YyM6ENyEdl7L9G8Au6awvGY',
    appId: '1:802280398317:ios:ba67122c33e765fdcfdbe4',
    messagingSenderId: '802280398317',
    projectId: 'foldious-ae650',
    storageBucket: 'foldious-ae650.firebasestorage.app',
    androidClientId: '802280398317-70o4469n74hpjsspln2vhi81iu0d1qm0.apps.googleusercontent.com',
    iosClientId: '802280398317-4lhcvq0t5v8j0c5hgnmqdu96totg923r.apps.googleusercontent.com',
    iosBundleId: 'com.foldious.storage',
  );
}